### PR TITLE
✨ replicate als overlay system

### PR DESCRIPTION
**Pull request by KptMonkey**
Replicates the ALS Overlay system
* Switching states is replicated
* Aiming is replicated

* The on possed logic is now separated into BeginPlay and OnPossesd such that the client gets also the input mapping assigned
* OverlaySate is a RepNotify
* SetOverlayStatetReplicated is a new function added to the OverlayGraph - it's called in the W_OverlayStateSwitcher
* OnRep_OverlayState is a new function (I can't move it to the Overlay Category)

It doesn't replicate the motion matching system, since I didn't wanted to touch the logic there. Since it's about the ALS part and it's so nicely separated in this project. 
* I had to change the "WantsToAim" boolean to replicated
* I had to expand the aiming logic by a bit, but the orginal code is still there.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Orientation on aim seems to be off by 90 degrees. If I face the one player and aim I am looking to that players left, if I face that direction and aim I am then looking away from the observer rather than aiming off to their left. Haven't even begun to look at your changes to see why, just the first thing I noticed when testing.

**Comment by IngCr3at1on** [comment]
@KptMonkey I'm admittedly new to Unreal so forgive me if this is a silly question but I'm wondering if there's a reason or benefit to using OnPossessed and BeginPlay for the controller instantiation vs something like Receive Controller Change?

**Comment by KptMonkey** [comment]
> @KptMonkey I'm admittedly new to Unreal so forgive me if this is a silly question but I'm wondering if there's a reason or benefit to using OnPossessed and BeginPlay for the controller instantiation vs something like Receive Controller Change?

It's just an easy setup and most people know what is happening. You can always change it in your own project

**Comment by KptMonkey** [comment]
> Orientation on aim seems to be off by 90 degrees. If I face the one player and aim I am looking to that players left, if I face that direction and aim I am then looking away from the observer rather than aiming off to their left. Haven't even begun to look at your changes to see why, just the first thing I noticed when testing.
> 
> Thinking about this I think better wording would be: the replicated aim is 90 degrees to my right vs where I'm aiming

I will have a look the next days

**Review by letsplaywithstrings — COMMENTED** [review]
As far as I think you can touch the whole logic to make it fully replicated.

**Comment by PolygonHive** [comment]
Project is now fully replicated with the 5.5 updates. Thanks for the help 👍

**Pull request closed without merging**
